version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  todoapi:
    build: ./todoapi
    environment:
      DATABASE_URL: postgresql://docker:password@postgres:5432/todolist
      PORT: 8080
      ADDR: 0.0.0.0
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
